AWSTemplateFormatVersion: '2010-09-09'
Description: 'Citizen Dispatch - a platform for coordinating emergency response efforts
  among citizen volunteers.

  '
Outputs:
  CitizenDispatchApi:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev
  QueryFunction:
    Description: GraphQL Query Lambda Function ARN
    Value:
      Fn::GetAtt:
      - QueryFunction
      - Arn
Parameters:
  ClientS3BucketName:
    Default: citizen-dispatch-sar
    Description: The bucket name to serve the client web application from
    Type: String
  ResourcePrefix:
    Default: citizen-dispatch-sar
    Description: The prefix for all resources created by this template.
    Type: String
Resources:
  CopyWebsiteFunction:
    Environment:
      Variables:
        API_ENDPOINT:
          Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/dev
        TARGET_BUCKET:
          Ref: ClientS3BucketName
    Events:
      Schedule:
        Rate: (1 minute)
    Policies:
      S3CrudPolicy:
        BucketName:
          Ref: ClientS3BucketName
    Properties:
      CodeUri: s3://citizen-dispatch/89618aea522e06800f7fb3ddc142aefa
      Handler: copyWebsiteBucket.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  DispatchesTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Fn::Sub: ${ResourcePrefix}-dispatches
    Type: AWS::DynamoDB::Table
  MissionsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Fn::Sub: ${ResourcePrefix}-missions
    Type: AWS::DynamoDB::Table
  QueryFunction:
    Properties:
      CodeUri: s3://citizen-dispatch/039baaee84a901d36d8cdc9899fc7b66
      Events:
        Query:
          Properties:
            Method: post
            Path: /query
          Type: Api
      Handler: server/handlers/query.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  ReportLocationFunction:
    Properties:
      CodeUri: s3://citizen-dispatch/039baaee84a901d36d8cdc9899fc7b66
      Events:
        Query:
          Properties:
            Method: post
            Path: /reportLocation
          Type: Api
      Handler: server/handlers/reportLocation.handler
      Runtime: nodejs8.10
    Type: AWS::Serverless::Function
  RequestsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Fn::Sub: ${ResourcePrefix}-requests
    Type: AWS::DynamoDB::Table
  StaticSite:
    Properties:
      AccessControl: PublicRead
      BucketName:
        Ref: ClientS3BucketName
      WebsiteConfiguration:
        ErrorDocument: index.html
        IndexDocument: index.html
    Type: AWS::S3::Bucket
  TeamsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Fn::Sub: ${ResourcePrefix}-teams
    Type: AWS::DynamoDB::Table
  UserLocationsTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      - AttributeName: timestamp
        AttributeType: N
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      - AttributeName: timestamp
        KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Fn::Sub: ${ResourcePrefix}-userLocations
    Type: AWS::DynamoDB::Table
  UserPool:
    Properties:
      DeviceConfiguration:
        ChallengeRequiredOnNewDevice: true
        DeviceOnlyRememberedOnUserPrompt: false
      Schema:
      - AttributeDataType: String
        Mutable: true
        Name: firstName
      - AttributeDataType: String
        Mutable: true
        Name: lastName
      SmsAuthenticationMessage: 'CitizenDispatch: {####}'
      SmsVerificationMessage: 'CitizenDispatch: {####}'
      UserPoolName:
        Fn::Sub: ${ResourcePrefix}-user-pool
      UsernameAttributes:
      - phone_number
    Type: AWS::Cognito::UserPool
  UserPoolClient:
    Properties:
      ClientName:
        Fn::Sub: ${ResourcePrefix}-app-client
      GenerateSecret: false
      UserPoolId:
        Ref: UserPool
    Type: AWS::Cognito::UserPoolClient
  UsersTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      TableName:
        Fn::Sub: ${ResourcePrefix}-users
    Type: AWS::DynamoDB::Table
Transform: AWS::Serverless-2016-10-31
